### ISSUE TITLE
可以使用 toBitmap 函数

### ISSUE THREAD

**Issue by SOCK-MAGIC** [SakurajimaMaii/VastUtils#55]
https://github.com/SakurajimaMaii/Android-Vast-Extension/blob/4d62ed3bfcf5d466ec06fa073af6da8630cafea2/libraries/VastTools/src/main/kotlin/com/ave/vastgui/tools/graphics/Bitmap.kt#L338
`androidx.core.graphics.drawable.toBitmap()`

**Comment by SakurajimaMaii** [comment]
非常感谢，我在前天已经了解到该函数，会在下一个版本进行替换
